### ISSUE TITLE
Did some behavior change with version 23?

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#110]
The Picoquic unit test for "session resume" are failing, following what looked like a change in behavior of the  ptls_handshake() API. In the regular case (without resume), the API return code is 0. But in the session resume case, after processing the client hello, ptls_handshake() returns PTLS_ERROR_IN_PROGRESS instead of 0.

The workaround is easy, but this is surprising.

**Comment by kazuho** [comment]
I believe that the behavior of `ptls_handshake` has not changed. The function continues to return zero when receiving ClientHello (note: once the function returns zero, you are no longer allowed to call `ptls_handshake`).

OTOH, since the merger of #109, 6 bytes of data (containing a ChangeCipherSpec record) is sent along with the ClientHello message. The record is left in the input buffer when `ptls_handshake` returns zero. If you try to consume that 6 bytes by calling `ptls_receive`, the function will return `PTLS_ERROR_IN_PROGRESS`.

The change was intentional; TLS stacks are allowed to send a ChangeCipherSpec message at that moment, and it is believed that doing so will improve the penetration rate (please refer to [tls13-draft-23 appendix D.4.](https://tlswg.github.io/tls13-spec/draft-ietf-tls-tls13.html#rfc.appendix.D.4)). My intuition was that always sending the message will lead to better testability.

However, it is not necessary to send ChangeCipherSpec message in QUIC. For test coverage, it is also beneficial to have a knob to turn the feature on/off.

Therefore, in 5268ba4, I have added a knob (`ptls_context_t::send_change_cipher_spec`) which is _off_ by default.

Does the above explain the issue you are seeing?

**Comment by huitema** [comment]
OK. I think it explains what I observed. But then, why did I see a different behavior on session resume and on regular setup?

**Comment by kazuho** [comment]
> But then, why did I see a different behavior on session resume and on regular setup?

ChangeCipherSpec message is sent when the payload becomes encrypted.

For a non-zero-RTT handshake, that means the beginning of the second flight, immediately before sending ClientFinished. That means that the server will receive ChangeCipherSpec after sending ServerFinished (i.e. when `ptls_handshake` returns zero).

For a zero-RTT handshake, that means the end of the first flight, immediately after sending ClientHello, because zero-RTT payload is encrypted.

Does this explanation make sense to you?

**Comment by huitema** [comment]
The explanation makes sense, and it points to an error in my code. I was looking at the return code of the "handshake" API to check whether the session was established. I should look instead at the function ptls_handshake_is_complete().
