### ISSUE TITLE
PR 111 (add aes256gcm / sha384 support) broke the TLS handshake

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#112]
Recent builds of PICOTLS have stopped interoperating with other TLS23 stacks. 

When receiving a Server Hello, ptls_handshake() returns an error 0x14, PTLS_ALERT_BAD_RECORD_MAC. This happens when decoding a record of type PTLS_CONTENT_TYPE_APPDATA, length 100 bytes, at line 3156 in picotls.c. The error happens in the call to "aead_decrypt", with algorithm  "AES128-GCM" (ptls_openssl_aes128gcm).

Blocking QUIC Interop...

**Comment by kazuho** [comment]
Thank you the details.

In 70cb4d0, AES256GCM_SHA384 cipher-suites have been removed from the default list until the issue gets fixed.

The issue is that when picotls acting as a client initiates a handshake, it starts calculating the handshake hash using the algorithm specified in it's most preferred cipher-suite, and that does not change even after the server selects another algorithm. So if the clients most-preferred cipher-suite is AES256GCM_SHA384 and the server selects a cipher-suite that specifies SHA256 as the hash function, handshake fails.

**Comment by huitema** [comment]
I verified that PR #113 fixed the issue.
