### ISSUE TITLE
Client certificate

### ISSUE THREAD

**Issue by bkchr** [h2o/picotls#116]
Does `picotls` already supports sending client certificates and the verification of these certificates?

After looking into the code, I'm not 100% sure, but assume that this is currently not supported.

**Comment by kazuho** [comment]
Your understanding is correct. Client authentication is not supported.

**Comment by bkchr** [comment]
@kazuho are you planning to support that in the near future? If not, could you give me some pointers where to start and then I could maybe create a pull request.

**Comment by kazuho** [comment]
@bkchr I am interested in having client authentication support in picotls (including post-handshake client authentication, since it will be used in [Secondary Certificates for HTTP/2 extension](http://httpwg.org/http-extensions/draft-ietf-httpbis-http2-secondary-certs.html)). But I do not have a plan to work on that right now; it would be great if somebody could work on the issue.

FWIW, I think we need to the following to reach MVP:
* add an option to `ptls_context_t` that instructs the server to request and enforce client authentication
* reuse `ptls_context_t::certificates`, `ptls_context_t::sign_certificate`, `ptls_context_t::verify_certificate` for client authentication
* when client authentication is required, delay the moment `ptls_handshake` returns zero to when the server receives ClientFinished

Then we can consider things like following:
* extend the option to specify client CAs (sent using certificate_authorities extension)
* add a callback on client-side that can be used to select the correct certificate based on the certificate_authorities extension

Does that make sense to you?

**Comment by bkchr** [comment]
I think that I can start with your information. If I got more questions, I come back to you :) Thanks :+1:

**Comment by aep** [comment]
btw @bkchr , i dont think we need PEM. Passing the curve directly from a char*  would be alot better for us since it gets loaded from a random source. Can that be done or does it conflict with existing API design?

**Comment by bkchr** [comment]
Nowhere we force loading the certificate as PEM.

**Comment by aep** [comment]
(clarified offline. it's actually already implemented)

**Comment by kazuho** [comment]
Let's close the issue now that we have #121 merged. Thanks for the great work, @bkchr!
