### ISSUE TITLE
Wrong transcript for binders in second ClientHello

### ISSUE THREAD

**Issue by ad-l** [h2o/picotls#124]
There appears to be a problem with the binders computed by picotls clients after HRR, which fail to verify both against OpenSSL and miTLS.

To reproduce, I used `picotls/cli -n -s session localhost 443` twice against `openssl s_server -www -accept 443 -msg` (which produces `error:141FA0FD:SSL routines:tls_psk_do_binder:binder does not verify:ssl/statem/extensions.c:1592:`) and `cmitls -s -hrr 0.0.0.0 443` (which fails with `AD_bad_record_mac (binder verification failed)`

**Comment by kazuho** [comment]
@ad-l Thank you for reporting the issue. It turns out that this is a regression caused by #114.

The issue happens when a server accepts a resumption using the PSK found in the _second_ ClientHello sent in response to a HelloRetryRequest. Picotls running as a server ignores any PSK binder found in the second CH; that is why we have not identified the issue in our unit tests.
