### ISSUE TITLE
delay passing handshake read key to QUIC until receiving EOED

### ISSUE THREAD

**Issue by kazuho** [h2o/picotls#175]
Otherwise, a QUIC stack could pass ClientFinished to picotls before EOED, which would terminate the handshake due to delivery of an unexpected message.

Note that our strategy is to delay passing of the keys until they are ready to be used (i.e. 1-RTT read key is passed to QUIC after receiving ClientFinished, even though it is known to the TLS stack at an earlier moment); the change proposed in this issue aligns with that.

Fixes https://github.com/quicwg/base-drafts/issues/1651.

**Comment by huitema** [comment]
Yes, that would help. Right now, I have code to mitigate the issue: Picoquic will only start feeding epoch N data to TLS if the epoch N stream is "closed". But I have to use heuristics to define "closed":
1) Epoch 0 (Initial) is closed if epoch 2 can be received. (Maybe I should add epoch 1.)
2) Epoch 1 is closed if the node is a client (servers don't send 0-RTT) or if 0-rtt is not enabled, or after 1 message is passed.
3) Epoch 2 is closed if handshake is complete.
I don't like heuristics so much, because they depend on knowledge of TLS.

**Comment by huitema** [comment]
Please don't check in these changes. The Quic server needs the handshake receive key at the same time as the handshake write key, because it has to process acks and retransmissions. Using the key provision to signal end of epochs only looks like a good idea, but it has unwanted side effects. It would be much better to have an independent signaling that an epoch is complete.

**Comment by kazuho** [comment]
Thank you for the comment. I am really glad that you noticed why we need to keep the code that exposes the handshake keys at the earliest moments.

OTOH, we need to look for a fix. We need to either let picotls accept the unordered delivery of EOED, or expose the current receive epoch to the QUIC stacks in some ways.

Do you have an opinion on how you want this to be fixed? Among the options discussed in https://github.com/quicwg/base-drafts/issues/1651#issuecomment-412393837 and Martin's following comment, I am slightly inclined to option a.

**Comment by huitema** [comment]
Option a is the cleanest. It is very easy for the Quic stack to hold onto data until the TLS stack is ready.

For me, the simplest would be an extra argument to ptls_handle_message. Something like that:
```
int ptls_handle_message(ptls_t *tls, ptls_buffer_t *sendbuf, size_t epoch_offsets[5], size_t in_epoch, 
                        size_t * next_epoch, const void *input,
                        size_t inlen, ptls_handshake_properties_t *properties)
```
The "next epoch" argument would return the value of the next epoch for with data should be provided.

**Comment by kazuho** [comment]
Glad to hear your opinion. I have created #177 that introduces a separate function to obtain the epoch rather than returning the value from the handshake function, because IMO we do not need to require each QUIC stack to remember the expected level (rather, they can call `ptls_get_read_epoch` every time to see what the expected level is). Please let me know what you think about the approach.

**Comment by huitema** [comment]
I just reviewed and approved PR #177. It is a nice design, removes the need for maintaining TLS receive state in the QUIC stack.
