### ISSUE TITLE
minicrypto equivalent of ptls_openssl_init_verify_certificate?

### ISSUE THREAD

**Issue by larseggert** [h2o/picotls#47]
Is there a minicrypto equivalent of the `ptls_openssl_init_verify_certificate()` function? The [wiki](https://github.com/h2o/picotls/wiki/Using-picotls) only discusses the openssl case for initializing a client context.

**Comment by kazuho** [comment]
> Is there a minicrypto equivalent of the `ptls_openssl_init_verify_certificate()` function?

No. Unfortunately not.

The reason we do not yet have written one for the minicrypto backend is decoding and validating X.509 certificate properly is hard, and I am not aware of a good small library that can that handle that. I would appreciate if anybody could point to me to a library that does just that, or even better come with a pull request that incorporates such library :-)

For the meantime, you can use the OpenSSL backend for signing and verifying the certificate. OTOH I think that you need to continue using the minicrypto backend, at least `ptls_minicrypto_cipher_suites`, since we cannot support AEAD _with AAD_ using an OpenSSL backend due to lack of API.

**Comment by kazuho** [comment]
> we cannot support AEAD with AAD using an OpenSSL backend due to lack of API

Minor correction. I have learned that OpenSSL can do AAD, and the necessary code has landed in 949ddb1. Also, kazuho/quic branch has been merged to master for our convenience.

**Comment by larseggert** [comment]
Thanks for the explanation! I'm now using the OpenSSL backend.
