### ISSUE TITLE
Crash in server_handle_hello()

### ISSUE THREAD

**Issue by larseggert** [h2o/picotls#48]
I see a crash at the end of `server_handle_hello()`, because `tls->ctx->sign_certificate->cb` is zero when called from the "build and send CertificateVerify" block.

I'm sure I'm doing something wrong when setting things up. Here is how I currently initialize the contexts:
```C
static ptls_minicrypto_secp256r1sha256_sign_certificate_t sign_cert;
static ptls_iovec_t tls_certs;
static ptls_verify_certificate_t verifier;

unsigned char tls_key[] = {
  0x30, 0x77, 0x02, 0x01, 0x01, 0x04, 0x20, 0xe6, 0xbd, 0x0f, 0xe0, 0xf2,
  // ...
};
unsigned int tls_key_len = 121;
unsigned char tls_cert[] = {
  0x30, 0x82, 0x01, 0x93, 0x30, 0x82, 0x01, 0x39, 0xa0, 0x03, 0x02, 0x01,
  // ...
};
unsigned int tls_cert_len = 407;

// initialize TLS context
tls_ctx.random_bytes = ptls_minicrypto_random_bytes;
tls_ctx.key_exchanges = ptls_minicrypto_key_exchanges;
tls_ctx.cipher_suites = ptls_minicrypto_cipher_suites;

ptls_minicrypto_init_secp256r1sha256_sign_certificate(
    &sign_cert, ptls_iovec_init(tls_key, tls_key_len));
tls_ctx.sign_certificate = &sign_cert.super;

tls_certs = ptls_iovec_init(tls_cert, tls_cert_len);
tls_ctx.certificates.list = &tls_certs;
tls_ctx.certificates.count = 1;

// TODO: there doesn't yet seem to be a minicrypto version of this call:
// ptls_openssl_init_verify_certificate(&verifier, 0);
tls_ctx.verify_certificate = &verifier;
```
Apart from the missing `ptls_openssl_init_verify_certificate` call (see #47), do you spot anything obviously bogus?

**Comment by kazuho** [comment]
I assume that this is because the length of the key passed to `ptls_minicrypto_init_secp256r1sha256_sign_certificate` is what is expected.

The function expects a _raw_ private key (i.e. 32 bytes long) as an argument, and returns an error if it is not (please see https://github.com/h2o/picotls/blob/47094f9/lib/uecc.c#L175-L176).

So what you need to do to fix the issue is to either change the key being passed to a raw private key. Alternatively, you can use the OpenSSL backend for signing the certificate ([t/cli.c](https://github.com/h2o/picotls/blob/47094f9/t/cli.c#L470-L482) has a code that loads and sets up a PEM-encoded private key).

**Comment by larseggert** [comment]
Is it possible to generate raw keys and certs with the `openssl` command line tools? That would be the easiest way forward for now. If not, I will investigate switching to PEM-encoded keys in files.

**Comment by larseggert** [comment]
Never mind, I figured out a way to extract the raw keying material. Thanks pointing me in the right direction!
