### ISSUE TITLE
Adding an extension in the handshake (for QUIC)

### ISSUE THREAD

**Issue by huitema** [h2o/picotls#55]
The QUIC spec requires sending the QUIC transport parameters as part of the handshake, as an extension. Is there an example somewhere on how to do that?

**Comment by kazuho** [comment]
IIRC support for extensions is not required for our hackathon in Prague, but below is what you should do:

`ptls_handshake_properties_t` is an object that can be used to pass / receive when performing a handshake. It is passed to`ptls_handshake` as the last argument. When performing a handshake, the last argument should either always be NULL or always point to the same object.

The object has three properties related to extensions.

`additional_extensions` should point to a list of extensions that needs to be sent to the peer. The list is terminated by its type parameter set to UINT16_MAX.

`collect_extension` is a callback that receives a extension type and returns a boolean value indicating if the extension should be recorded.

`collected_extensions` if a callback that is called during handshake when the TLS stack has received all extensions. Only the extensions for which the `collected_extension` returned true are collected.

When running as a server, it is possible (and makes sense) to update `additional_extensions` when your `collected_extensions` gets invoked, so that you could return an extensions that responds to the extension sent from the client.

You should zero-clear properties of `ptls_handshake_properties_t` that you are not interested in using.

For an example, I recommend consulting [lib/quicly.c](https://github.com/h2o/quicly/blob/1c5929e/lib/quicly.c). It sets `additional_extensions` and also defines three callback functions related to extension handling: `collect_transport_parameters`, `server_collected_extensions`, `client_collected_extensions`.

**Comment by huitema** [comment]
Thanks. That also answers my questions about using extractors, the code is easy to understand.
