### ISSUE TITLE
Implement premaster/SSLKEYLOGFILE 

### ISSUE THREAD

**Issue by alagoutte** [h2o/picotls#6]
Can you add support of new ke for SSLKEYLOFILE (premaster)

https://boringssl-review.googlesource.com/#/c/8841/

I will be help to add decrypt on #wireshark

**Comment by kazuho** [comment]
@alagoutte Thank you for the suggestion, I am fine to adding such support.

OTOH, would you please specify which key you'd want to use using the terms of [section 7.1](https://tlswg.github.io/tls13-spec/#rfc.section.7.1)? There is no longer a premaster key in TLS 1.3.

**Comment by alagoutte** [comment]
Hi Kazuho,

Sorry i have post the wrong link..
the idea is use the same like boringssl (and nss) : https://boringssl-review.googlesource.com/#/c/8841/

**Comment by kazuho** [comment]
@alagoutte Thank you for updating the link! Does the spec. on this commit message conform to what you are expecting? https://boringssl.googlesource.com/boringssl/+/e776cc29568e520aaabc83188cc7db7991f0b776%5E!/

**Comment by kazuho** [comment]
I am not sure if the specification in the boringssl commit comment (shown below) is what you want.

```
    EARLY_TRAFFIC_SECRET <client_random> <early_traffic_secret>
    HANDSHAKE_TRAFFIC_SECRET <client_random> <handshake_traffic_secret>
    TRAFFIC_SECRET_0 <client_random> <traffic_secret_0>
```

The spec. defines log keys for various traffic secrets, without designation of the traffic secret being server-side or client-side (note that TLS 1.3 draft (as of today) uses different traffic secrets for data sent by client and those sent by server).

I assume you want to log data sent by both client and the server. Considering that, you would need two traffic keys (the one used by the client and the other by the server) logged for each phase of the handshake.

Or the other way would be to log the secrets that are used to derive the traffic secrets. In this case, I believe we should not include `traffic_` in the key names of the log file, since it would be confusing.

@alagoutte WDYT? Should we ask on the mailing list?

**Comment by alagoutte** [comment]
Hi,

Yes, May be need to make some change on boring ssl specifications (make on old TLS 1.3 draft release)

Yes, the better will be ask on mailing list 

@lekensteyn can you look also ?

**Comment by Lekensteyn** [comment]
Hmm, [TLS 1.3 draft -17](https://tools.ietf.org/html/draft-ietf-tls-tls13-16#section-7.1) indeed has two distinct secrets now for client/server side. One possibility is to use server random for the server side with an additional tag (otherwise you cannot know whether you have the server or client side key). E.g.:

    SERVER_EARLY_TRAFFIC_SECRET ...
    CLIENT_EARLY_TRAFFIC_SECRET ...

Note that the client random was only used as identifier because it always exist (unlike session ID) and is quite unique. If there is some other unique identifier then it would also be OK.

**Comment by kazuho** [comment]
> One possibility is to use server random for the server side with an additional tag (otherwise you cannot know whether you have the server or client side key). E.g.:
> ```
> SERVER_EARLY_TRAFFIC_SECRET ...
> CLIENT_EARLY_TRAFFIC_SECRET ...
> ```

That would work for me. Note that you still need to expand the key and iv from the traffic secrets, as defined in [section 7.3](https://tlswg.github.io/tls13-spec/#rfc.section.7.3), and that [the formula is going to change in draft 17](https://github.com/tlswg/tls13-spec/pull/699).

**Comment by Lekensteyn** [comment]
Hey @kazuho, see the above linked commits for the format. TLS 1.3 decryption is now implemented in Wireshark for handshake and application traffic. For 0-RTT the key will probably be `CLIENT_EARLY_TRAFFIC_SECRET` (same name as TLS 1.3 spec), but I cannot test it yet.

**Comment by kazuho** [comment]
@Lekensteyn Thank you for the update!

I've added secret logging to picotls. It also logs `CLIENT_EARLY_TRAFFIC_SECRET`, an example can be found in the comment in the PR.

Please let me know if you see any issue.

**Comment by Lekensteyn** [comment]
As reported in https://github.com/h2o/picotls/pull/25#issuecomment-278034145, decryption works (but there is a memleak). With some additional patches to fix NewSessionTicket dissection in Wireshark, everything can be decrypted.

**Comment by Lekensteyn** [comment]
@kazuho I think that this issue can be closed since it is already implemented.

h2o still needs an option to set the callback though :)

**Comment by kazuho** [comment]
Yay!

**Comment by 500646** [comment]
is there any way to dcrypt the https traffic at server side with h2o?

**Comment by Lekensteyn** [comment]
@500646 nope, it is not supported. To do this, you would have to set `pctx->ctx.log_secret` in `listener_setup_ssl_picotls` (h2o `src/main.c`) to an appropriate value.
